### ISSUE TITLE
Clarify comment on `PhysicalDeviceSelector::allow_fallback_gpu`

### ISSUE THREAD

**Issue by DethRaid** [charles-lunarg/vk-bootstrap#11]
What's a fallback GPU? is there a fallback order defined somewhere? Can I set which kind of GPU I want to fall back to?

**Comment by charles-lunarg** [comment]
The fallback gpu should be renamed fallback gpu type, as its what type of gpu to fallback on (integrated, discrete, etc).

**Comment by charles-lunarg** [comment]
I've renamed it to `allow_fallback_gpu_type` but that is unsatisfactory. `allow_fallback_to_non_preferred_gpu_type` is much clearer but a lot less fun to read. Suggestions are welcome :)

**Comment by charles-lunarg** [comment]
I have renamed it again to `allow_any_gpu_device_type` as thats what it is doing. The selection logic first checks if the device type matches the selection criteria. If it doesn't, it then will remove that gpu from consideration if `allow_any_gpu_device_type` is false, and it will mark it partially acceptable if it is true.
This change is in the latest commit, closing cause it should be much clearer now.
