### ISSUE TITLE
How do i get rid of this.

### ISSUE THREAD

**Issue by Ma-Y** [charles-lunarg/vk-bootstrap#119]
[ERROR: Validation]
Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x7ff407ee6790, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x7ff407ee6790[] supports it The Vulkan spec states: If the VK_KHR_portability_subset extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensions must include "VK_KHR_portability_subset" (https://vulkan.lunarg.com/doc/view/1.2.198.1/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)

**Comment by charles-lunarg** [comment]
You enable the extension if it is present.
This isn't well supported by vk-bootstrap currently, but it should be extremely easy to do with the phyiscal device selector
```cpp
vkb::PhysicalDeviceSelector selector(inst);
selector.add_desired_extension(VK_KHR_portability_subset);
// do the rest of your physical device setup.
```
