### ISSUE TITLE
Wrong test in get_dedicated_queue_index()

### ISSUE THREAD

**Issue by YvesBoyadjian** [charles-lunarg/vk-bootstrap#129]
At line 973 of VkBootstrap.cpp, there is the code : 

`if ((families[i].queueFlags & desired_flags) && (families[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) == 0 &&`

but the right code must be : 

`if ((families[i].queueFlags & desired_flags) == desired_flags && (families[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) == 0 &&`

Same thing for get_first_queue_index() and get_separate_queue_index()

**Comment by charles-lunarg** [comment]
Yes, I believe you are correct. I looked through the code and I didn't see any cases where this would be wrong (as `desired_flags` is always a single bit) but this would be better for future code which may not make that assumption. PR's are welcome :)
