### ISSUE TITLE
I should be able to request device extensions through DeviceBuilder

### ISSUE THREAD

**Issue by DethRaid** [charles-lunarg/vk-bootstrap#13]
Unless it uses the extensions from the physical device? If so, that should be documented

**Comment by charles-lunarg** [comment]
The extensions must be supported by the device, and should be apart of which physical device you choose. When you add required extensions to the physical device selector, it propogates them and automatically enables them in the device.

**Comment by charles-lunarg** [comment]
Documented and in the latest commit.
