### ISSUE TITLE
Feature Request: Extend VkBootstrapDispatch.h to include a dispatch table for Instance functions

### ISSUE THREAD

**Issue by Valakor** [charles-lunarg/vk-bootstrap#136]
I've recently started using vk-bootstrap to replace my personal hacky boilerplate, and thought it would be nice if I could completely remove my dependency on volk by using `vkb::DispatchTable`; however, I'm left having to manually fetch instance functions like `vkGetPhysicalDeviceProperties` because vkb only exposes device-level functions.

Many (all?) of the functions I need already get fetched by vkb's implementation and stored in `vkb::detail::VulkanFunctions`, but are inaccessible to me externally. It'd be nice if either the existing function table was made publicly accessible, or an alternative one was generated as part of VkBootstrapDispatch.h.

**Comment by charles-lunarg** [comment]
Question: Which functions do you actually need? 

One of my reasons for not exposing the instance functions was because vk-bootstrap should be able to do all the instance level calls necessary. I realize now that surface related calls aren't handled so there definitely are holes. 

It wouldn't be hard to add, since the autogen would just need to generate a different struct containing those function pointers.

**Comment by Valakor** [comment]
So far I've only needed `vkGetPhysicalDeviceProperties`, `vkGetPhysicalDeviceMemoryProperties`, and `vkGetPhysicalDeviceMemoryProperties2`, though only because VulkanMemoryAllocator requires them as I've disabled its ability to look them up dynamically.

I don't think that vk-bootstrap will ever be able to handle _all_ instance-related things (and I don't think it should), so exposing instance-level functions like device-level functions seems like a reasonable way to use the library as intended while also supporting uncommon edge cases or integrations with other libraries.

**Comment by charles-lunarg** [comment]
Hmmm the need for other libraries makes it clear it should export them wholesale. 

And I agree, vk-bootstrap shouldn't be an everything library. That isn't its designed purposed.
