### ISSUE TITLE
Swapchain builder: image_count is set to minImageCount+1; consider providing a way to override it?

### ISSUE THREAD

**Issue by yoanlcq** [charles-lunarg/vk-bootstrap#137]
Hi,

In my engine I'd like the ability to choose how many images a swapchain should have, since I assume it involves a trade-off between memory consumption and the probability that the next image is ready for use as we acquire it.

The relevant part of the code is :

```cpp
detail::Result<Swapchain> SwapchainBuilder::build() const {
        // ...
	uint32_t image_count = surface_support.capabilities.minImageCount + 1;
	if (surface_support.capabilities.maxImageCount > 0 && image_count > surface_support.capabilities.maxImageCount) {
		image_count = surface_support.capabilities.maxImageCount;
	}
        // ...
```

Adding this feature via a PR is easy enough (I'd be happy to do it), but seeing how "confidently" the code chooses `minImageCount + 1`, I'm now wondering if my request makes sense in practice.

Out of curiosity, is it really so beneficial to favor a triple-buffering setup over double-buffering? (was this observed in practice?)
Is it a bad idea nowadays to prefer double buffering in order to spare some resources, but possibly at the expense of presentation rate?

Thanks!

**Comment by charles-lunarg** [comment]
I think the original code should be amended. This logic was a bit ad hoc, taken from my own code and other only samples. The +1 is from such code.

Being able to *set* the image count directly is technically impossible, as the number is decided by the presentation engine ultimately. All we can do is set the absolute min and max and the presentation engine will choose something in between.

**Comment by yoanlcq** [comment]
Alright, thanks! Then I'll submit a PR for that some time later today, if that's OK.

I think the API should just provide `set_desired_min_image_count()`, and the value is clamped when building; otherwise, if that is not used, then keep the default behavior of `minCount+1`.
The most flexible way would be to provide a function pointer to select the image count from the min and max, but that looks too overkill and niche to be worth it.

**Comment by charles-lunarg** [comment]
Closed as resolved.
