### ISSUE TITLE
Getting the queue indices and queues from a device should be instance methods on `vkb::Device` instead of free functions

### ISSUE THREAD

**Issue by DethRaid** [charles-lunarg/vk-bootstrap#14]

**Comment by charles-lunarg** [comment]
vkb::Device was meant to be a dumb struct holding the VkDevice for users to pull out and do whatever with. That doesn't mean I'm against adding functions to it, as it does hold the indexes needed to access the queues.

**Comment by charles-lunarg** [comment]
Most recent commit refactors queue getting (yet again). Made it a member function and simplified the interface as well.
