### ISSUE TITLE
Set missing cmake function IMPORTED_LOCATION

### ISSUE THREAD

**Issue by FrankXie05** [charles-lunarg/vk-bootstrap#148]
Hi, I'm the maintainer of vcpkg.
We have a problem maintaining our use of `vk-bootstrap`.

Reason: At present, our version is relatively backward, and the *-config.cmake file used by the exported cmake is provided by us, because `vk-bootstrap` has not yet exported the usage. But currently I see `vk-bootstrap` exporting cmake usage here:https://github.com/charles-lunarg/vk-bootstrap/blob/b01b2b1d8ef3fb1d784f1f53d716995855d89ea2/CMakeLists.txt#L79, I tried to update to latest commit, but failed. 😔

Purpose: 

1. Whether `vk-bootstrap` can release a new version in the short term to use the official `find_package`.
2. If not, whether to use the patch I applied.
3. For `vk-bootstrap`, is there currently a library that distinguishes static (lib) and dynamic (dll) to improve my patch. :)
cc @[spnda](https://github.com/spnda)

Related: vcpkg pull request: https://github.com/microsoft/vcpkg/pull/25210

Hope to get a reply soon. 🧐

**Comment by charles-lunarg** [comment]
Apologies for the delay in replying, I was away from the online realm for a bit.

I'm going to be honest and remark that I am not super familiar with how cmake installs/packages stuff nor how vcpkg works (even if I've used it before).

https://github.com/charles-lunarg/vk-bootstrap/commit/f839350318d5587f9a767fbfcbffbeea2989ecbb

This change added the relevant change, should the change not have included `EXPORT vk-bootstrap-targets`?

When you say you tried to update to the latest commit and failed, are you talking about tip of tree vk-bootstrap? What failure did you receive?

My response to the numbered list:
1. I'd be more than happy to update vk-bootstrap to fix this issue. But what does use "official `find_package`" mean?
2. Where is the patch? On the linked PR to vcpkg I think, but I just want to double check.
3. "Is there currently a library that distinguishes static and dynamic" I'm sorry, but I don't understand? vk-bootstrap tries to be flexible in its usage, and doesn't specify which kind of library it is (though, I suspect it should always be static, as that was how I assume it'll be used).

**Comment by FrankXie05** [comment]
@charles-lunarg 
I'm sorry for the confusion caused.
1. At present, the configuration file for exporting cmake usage of `vk-bootstrap` on `vcpkg` is provided by us. https://github.com/microsoft/vcpkg/tree/master/ports/vk-bootstrap (There is a problem now, I am fixing it), this is because the version is too early and `vk-bootstrap` did not export cmake usage at that time, but now `vk-bootstrap` has .
2. For the official `find_package()`, we want to use the official cmake export instead of ours (meaning unofficial)
3. For static libraries and dynamic libraries, I am not sure but currently vk only generates static libraries when using it.

**Comment by charles-lunarg** [comment]
I do see the issue with not setting the IMPORTED_LOCATION stuff, it generate warnings in other peoples projects, which is unfortunate.

FYI I intended this library to be used like a static library, not a dynamic one. I am not sure what issues are to be had by using vk-bootstrap as a shared library. However, I never specified STATIC in the cmakelists.txt, so thats on me. My question is if adding STATIC would break anybody or anything.

I'm still not sure what changes I need to make to the project. I am happy to work on a PR, or review one you create.

**Comment by FrankXie05** [comment]
@charles-lunarg 
Does not require you to modify anything
Expect: 
1. When will the new version be released (version 5.0 is not configured with cmake everywhere, it is present on the master branch and we want to update to a stable release version)
2. I submitted this issue mainly to ask the time of the release and some necessary questions (I think I have already got the answer)
3. For the setting of `IMPORTED_LOCATION`, it will be considered an `error` if it is not set before (this is why I want to set it), but now it is just a warning, I want to enable the official vk cmake configuration instead of the one we provide.

**Comment by charles-lunarg** [comment]
@FrankXie05 

I did a whole big refactor of cmake & the install code with PR #231 

Wondering if I can close this issue as well as your thoughts on that PR.

**Comment by FrankXie05** [comment]
@charles-lunarg Yes. Thanks, I will update to the latest version to adapt to it. :)

**Comment by charles-lunarg** [comment]
Awesome! Thanks for doing that - makes me happy to see it made available through vcpkg :)
