### ISSUE TITLE
Implement Pipeline Creation Builders

### ISSUE THREAD

**Issue by Diamond-D0gs** [charles-lunarg/vk-bootstrap#149]
Something in line with the builders used in VKB currently to help reduce the mess of structs involved when creating pipelines.

**Comment by charles-lunarg** [comment]
We worked on this in the past, but because pipelines have evolved so much over time, it'd really be better done with code-gen, at which point you might as well generate initializers/builders for the whole API.

Its a nice to have, but not a priority and makes the library loose focus.
