### ISSUE TITLE
Desired extensions not added to created physical device's extensions

### ISSUE THREAD

**Issue by sibaku** [charles-lunarg/vk-bootstrap#156]
When adding desired extensions to a **VkPhysicalDeviceFeatures**, they are checked, but not included in the final .extensions property of the **PhysicalDevice**.

In the _fill_out_phys_dev_with_criteria_ lambda inside _PhysicalDeviceSelector::select_impl_ (https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L1196) the list of all extensions is cleared and then the required ones are inserted. Afterwards the desired extensions are checked against the list of now just the required ones, resulting in no desired extensions being found, thus missing from the final list.

Moving the line `auto desired_extensions_supported = detail::check_device_extension_support(phys_dev.extensions, criteria.desired_extensions);` above `phys_dev.extensions.clear();` solves the issue:

```
auto desired_extensions_supported = detail::check_device_extension_support(phys_dev.extensions, criteria.desired_extensions);
 
phys_dev.extensions.clear();
phys_dev.extensions.insert(
		  phys_dev.extensions.end(), criteria.required_extensions.begin(), criteria.required_extensions.end());
phys_dev.extensions.insert(
		  phys_dev.extensions.end(), desired_extensions_supported.begin(), desired_extensions_supported.end());
```

**Comment by charles-lunarg** [comment]
Whoops!
Thanks for the catch, I've updated master with a fix.
Feel free to reopen if it doesn't solve the issue.
