### ISSUE TITLE
Bugs in SystemInfo()

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#16]
https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L166 missing strcmp

https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L171
should read `this->available_layers = available_layers.value ();`

**Comment by charles-lunarg** [comment]
Ah, this is what I get for writing code at 2am.
Thanks for pointing it out!
Fixed in the latest commit.
