### ISSUE TITLE
Allow to disable tests if built as a standalone

### ISSUE THREAD

**Issue by SpaceIm** [charles-lunarg/vk-bootstrap#165]
Tests & examples can't be disabled if vk-bootstrap is built from top CMakeLists directly.

Please replace by this logic for example:

```cmake
if(CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME)
    set(VK_BOOTSTRAP_TEST_DEFAULT_VALUE ON)
else()
    set(VK_BOOTSTRAP_TEST_DEFAULT_VALUE OFF)
endif()
option(VK_BOOTSTRAP_TEST "Test Vk-Bootstrap with glfw and Catch2" ${VK_BOOTSTRAP_TEST_DEFAULT_VALUE})

if(VK_BOOTSTRAP_TEST)
    add_subdirectory(ext)
    add_subdirectory(tests)
    add_subdirectory(example)
endif ()
```

(but I would advice to always disable `VK_BOOTSTRAP_TEST` by default, and enable it in your CI files)

**Comment by charles-lunarg** [comment]
@SpaceIm Done

Thats definitely an oversight on my part, thanks for catching it. And for providing a *very* clean solution.
