### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by SpaceIm** [charles-lunarg/vk-bootstrap#167]
@charles-lunarg The latest tag is 0.5, and it's 9 months old. In the meantime, there were few important fixes on macOS in vk-bootstrap like `VK_KHR_portability_subset` & `VK_KHR_portability_enumeration` support. Could you release a new version please?

**Comment by charles-lunarg** [comment]
@SpaceIm I just pushed up v0.6 (and included a quick summary of changes/fixes in the tag)

Apologies for forgetting about this issue for 2+ weeks...

**Comment by SpaceIm** [comment]
thanks
