### ISSUE TITLE
VKB console printing is undesirable

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#179]
I dislike that vkb is printing to the console via printf. Either the behaviour I perform is legal, then no message, or illegal, then fail the creation. This middle ground is poor.

Especially because:
1) I am not calling `add_required_extension_features` at all! There is no way to prevent seeing this message if I am using a VkPhysicalDeviceFeatures2 in the pNext chain.
2) It is not putting a \n at the end of the print, messing up my console output.

**Comment by charles-lunarg** [comment]
The purpose of the debug callback is for things that use debug utils to be able to report something back to the user. Vk-bootstrap doesn't use the callback to report information to the user, typically it errors out (with an error code in the Result type).

1. Can you add more details about what is happening? Which message are you seeing? That is likely a validation layer issue, and is something that vk-bootstrap may be doing incorrectly. 
2. Yes, that is an oversight.

I will say that you can easily add your own debug callback.

**Comment by martty** [comment]
I realize now I forgot to paste here the offending line:
https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L1520

**Comment by charles-lunarg** [comment]
Ah...
Well then I am in the wrong, and there indeed is a printf statement. 
Should this go through the debug callback as 'info' level?
I almost think it should just be removed, and made into documentation for the `add_pNext` function.

**Comment by martty** [comment]
If you can't make it unsurprising, then I think forbidding (and making it into an error) is the way to go.

**Comment by charles-lunarg** [comment]
Hmmm yeah, easier to forbid it. Plus, vk-bootstrap seeks to make it unnecessary to the stuff vk-bootstrap does for you. If a user feels the need to do what that printf calls out, its kinda failed.

**Comment by martty** [comment]
To clarify, I mean here that the user gives conflicting info to vkb. I think using either of the methods should be fine. But vkb could detect if the user tries to use both methods at the same time and refuse to build a device.
