### ISSUE TITLE
Nvidia Linux, validation error when creating a Vulkan instance

### ISSUE THREAD

**Issue by warriormaster12** [charles-lunarg/vk-bootstrap#185]
VkBootstrap seems to be throwing a validation about VK_KHR_PORTABILITY_ENUMIRATION since it is an extension listed in vulkaninfo for my gpu. It doesn't cause any type of issues with the application itself but it is still annoying to get this kind of an error.

`[ERROR: Validation]
Validation Error: [ VUID-VkInstanceCreateInfo-flags-zerobitmask ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x618984d2 | vkCreateInstance: parameter pCreateInfo->flags must be 0. The Vulkan spec states: flags must be 0 (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkInstanceCreateInfo-flags-zerobitmask)
[WARNING: Validation]
Validation Warning: [ VUID_Undefined ] Object 0: handle = 0x65c550, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x79de34d4 | Instance Extension VK_KHR_portability_enumeration is not supported by this layer.  Using this extension may adversely affect validation results and/or produce undefined behavior.`

**Comment by warriormaster12** [comment]
Creating an instance 

`void VulkanDevice::Init(){
    ENGINE_INFO( "Initializing Vulkan Device" );

    volkInitialize();


    vkb::InstanceBuilder builder;

    auto inst_ret = builder.set_app_name("Rusty Engine")
    .request_validation_layers(true)
    .require_api_version(1,3,0)
    .use_default_debug_messenger()
    .build();

    vkb_inst = inst_ret.value();

    instance = vkb_inst.instance;
    volkLoadInstance(instance);
    debugMessenger = vkb_inst.debug_messenger;

    ENGINE_INFO("Vulkan instance created");
}`

**Comment by charles-lunarg** [comment]
This sounds like older validation layers, which wouldn't know about the new bit.
If that isn't the case, then this issue should be moved to the validation layers repo since it is indeed a spurious error.

**Comment by warriormaster12** [comment]
I'll check Nobara's validation layer package.

**Comment by charles-lunarg** [comment]
Considering the bit was added in the 1.3.208 headers, yes that version is missing them.
https://github.com/KhronosGroup/Vulkan-Docs/commit/e88e27f2cda370444f87fc724412a384cb958824

**Comment by warriormaster12** [comment]
@charles-lunarg closing the issue since I'm getting no validation errors after moving away from system package to Vulkan SDK package.
