### ISSUE TITLE
request_validation_layers is broken

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#20]
https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L483

should probably read

`detail::check_layer_supported (system.available_layers, detail::validation_layer_name);`

**Comment by charles-lunarg** [comment]
Oops, that was an obvious mistake.
Thank you for reporting!

**Comment by charles-lunarg** [comment]
Fixed in the latest commit.
