### ISSUE TITLE
Requesting API versions is broken

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#21]
https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L298

I think should read

`			VkResult res = pfn_vkEnumerateInstanceVersion (&queried_api_version);`

**Comment by charles-lunarg** [comment]
Ah yes, that is wrong.
The title of the issue leads me to think this isn't the only issue, but no other ones are mentioned. Is that the case or did you find more problems?

**Comment by martty** [comment]
Sorry, may have been too dramatic :). Without this I think it always gives a 1.0 context. That is the only thing I found.

**Comment by charles-lunarg** [comment]
Ah haha, well you certainly got my attention!
I have pushed the fix up, but would love a double check if that was the solution.

I need to rewrite the tests, but many functions of this library are very hard to test without appropriate hardware.

**Comment by martty** [comment]
With the fix I can successfully get a 1.1 context (which I know because of the negative viewport height no longer being an error)!

**Comment by charles-lunarg** [comment]
:+1:
