### ISSUE TITLE
VS2022 build issue, missing return

### ISSUE THREAD

**Issue by CwTCwT** [charles-lunarg/vk-bootstrap#218]
move operator doesnt contain return, added it (return *this) locally, worked.
(only needed when warnings are treated as errors, at least on my side)

    Result& operator=(Result&& result) noexcept {
        m_init = result.m_init;
        if (m_init)
            new (&m_value) T{ std::move(result.m_value) };
        else
            m_error = std::move(result.m_error);
        **return *this;**
    }

BTW: hope its ok to inform you using this way :D

**Comment by charles-lunarg** [comment]
Whoops! 
Certainly looks silly on my part to forget that. Course, its been almost 3 years since that Result type was written, surprised nobody else has reported that issue earlier.

**Comment by CwTCwT** [comment]
> Whoops! Certainly looks silly on my part to forget that. Course, its been almost 3 years since that Result type was written, surprised nobody else has reported that issue earlier.

possibly only me compiles with warnings as errors :D
very fast fixed, thx
