### ISSUE TITLE
Feature Request: Improve extension selection functions

### ISSUE THREAD

**Issue by DexterHaxxor** [charles-lunarg/vk-bootstrap#224]
Add `vkb::InstanceBuilder ::enable_extensions` just like `vkb::PhysicalDeviceSelector:: add_required_extensions`. Add overloads to both that take `(const char* const *extensions, size_t count)` and `(const std::vector<const char*> &extensions)`, additionally something with a `std::span` if C++20 is enabled.

This should avoid using for-loops or pointless allocations when using things like `SDL_Vulkan_GetInstanceExtensions`.

**Comment by charles-lunarg** [comment]
Thought this was a much bigger request than it actually ended up being...

Apologies for taking so long to get back to you.

Would absolutely appreciate review & critique. Simple PR, but I'm sure I could have messed something up.

**Comment by monomere** [comment]
Not sure if I should make a new issue, but the pr didn't seem to add a `std::span` version of the extensions. Afaik, you can pass containers into `std::span` directly even, so the vector overload would be unnecessary. I'll try making a pr for this  today.

**Comment by charles-lunarg** [comment]
The library is currently C++17.
Not sure there is an easy way to add a C++20 feature that would be 'backwards compatible', though I am open to PR's.

And yes, you should create a separate issue to better track it (cause this issue is closed and I will forget)

**Comment by monomere** [comment]
ill make the issue later today, but the easiest way to check for the language version is to do something like this:
```cpp
#if __cplusplus >= 202002L
#include <span>
#endif
```

**Comment by monomere** [comment]
it's in the standard (the number itself comes from the year and month i think) [cppreference](https://en.cppreference.com/w/cpp/preprocessor/replace#Predefined_macros)

**Comment by charles-lunarg** [comment]
Have I been living under a rock???
Apparently because I either forgot about that or never knew it in the first place.
Looking forward to that PR.
