### ISSUE TITLE
Dispatch table function arguments lose `const` qualifier

### ISSUE THREAD

**Issue by Valakor** [charles-lunarg/vk-bootstrap#239]
See the generated method `DispatchTable::cmdSetBlendConstants(VkCommandBuffer commandBuffer, float blendConstants[4])`. The argument `blendConstants` should be declared as `const float blendConstants[4]` to match the declaration of `PFN_vkCmdSetBlendConstants` / `vkCmdSetBlendConstants`.

As far as I'm aware this is the only method like this and it's easy enough to work around by just calling through the dispatch table's `fp_vkCmdSetBlendConstants` instead.

**Comment by charles-lunarg** [comment]
Good eye! Not sure how hard it will be to fix, that is one of the annoying parts of autogen using vk.xml cause it requires manually parsing the parameters. But should be straightforward I think.
