### ISSUE TITLE
`destroy_*` functions pass arguments by value

### ISSUE THREAD

**Issue by monomere** [charles-lunarg/vk-bootstrap#243]
`Device` is a pretty large struct (last time I checked, ~2k bytes, but things might've changed. my point still stands though)

so if you do `destroy_device(my_device)`, all of that stuff is copied (the vulkan structs (PhysicalDeviceFeatures, etc.) specifically take up a lot of space), which is unnecessary.

imo it would be better to pass either by a non-const reference or by rvalue reference (to use move semantics for destruction), or have two overloads

sorry for a very low-effort issue, its late for me right now and I just remembered about this (I would forget otherwise)

**Comment by charles-lunarg** [comment]
Good eye - The other destroy functions passed by const ref so I believe it was a mistake to not pass by const ref.

And you are absolutely right about the size of the structures. A majority of it comes from PhysicalDevice, which is comprised of PhysicalDevice<Properties|Features|MemoryProperties> which combine together into a big struct.
