### ISSUE TITLE
Avoid including vulkan.h in headers

### ISSUE THREAD

**Issue by JuanDiegoMontoya** [charles-lunarg/vk-bootstrap#250]
On Windows, vulkan.h transitively includes windows.h, which itself is heavy and contains a lot of symbols and macros that tend to conflict with common code. vulkan_core.h can instead be used when platform-specific types are not needed.

In a quick test, replacing `#include <vulkan/vulkan.h>` with `#include <vulkan/vulkan_core.h>` in VkBootstrap.h and VkBootstrapDispatch.h seems to work on Windows. Doing this solves the issue of windows.h leaking into the user's code, but I don't know if this will cause a regression on other platforms.

**Comment by charles-lunarg** [comment]
The only thing that would be a problem is any user who was accidentally depending on windows.h stuff that vkbootstrap.h provided.

That said, the compile time benefit (and sanity) of not including windows.h does outweigh that potential breakage.
