### ISSUE TITLE
Possible typo in getting_started.md?

### ISSUE THREAD

**Issue by sishoo** [charles-lunarg/vk-bootstrap#258]
In getting_started.md there is this piece of code:

```
queue_descriptions.push_back (vkb::CustomQueueDescription (
            i, queue_families[i].queueCount, 
            std::vector<float> (queue_families[i].queueCount, 1.0f)));
```

but the struct ```vkb::CustomQueueDescription``` only has 2 things:
```
struct CustomQueueDescription {
    explicit CustomQueueDescription(uint32_t index, std::vector<float> priorities);
    uint32_t index = 0;
    std::vector<float> priorities;
};
```

Notice the extra ```queue_families[i].queueCount``` in getting_started.md.

The compiler says that no constructor matches it.

**Comment by charles-lunarg** [comment]
Thank you for bringing this up, I've gone ahead and fixed getting_started.md with the appropriate changes (as well as a quick update to other things that were out of date)
