### ISSUE TITLE
Finish up swapchain builder

### ISSUE THREAD

**Issue by charles-lunarg** [charles-lunarg/vk-bootstrap#26]
Currently, the swapchain builder works but was thrown together without much direction. 

It should be polished up to the same standard as the rest of the library and be a viable builder for people to use in lieu of writing it out themselves.

**Comment by martty** [comment]
+1: currently it is not possible to specify swapchain image usage

**Comment by charles-lunarg** [comment]
I can add that capability rather easily, but what else would you like to see changed?
I am looking through VkSwapchainCreateInfoKHR and finding that I could allow users to specify all sorts of options, though I'm not sure what is beneficial and what isn't needed to be configured.

**Comment by martty** [comment]
I am not sure I would use something else at the moment, this seems to be biggest for me.

**Comment by charles-lunarg** [comment]
I have added image usage flags in the latest commit as well as array layer count and whether to clip it, since those are all simple additions.
Things like the preTransform and composite alpha I leave as future things to decide.

**Comment by charles-lunarg** [comment]
Went ahead and added the preTransform and composite alpha, as well as redid the recreatation aspect. This means that for the time being, the swapchain builder is feature complete. Closing the issue but may reopen it if the design needs a rework later on.
