### ISSUE TITLE
Make it possible to check what features have been enabled

### ISSUE THREAD

**Issue by n0F4x** [charles-lunarg/vk-bootstrap#277]
With the help of the recent API `PhysicalDevice::enable_extension_features_if_present` we get a way to enable optional device extension features, but there is no way to ask what features have been enabled afterward.

The same getter is already present for simple device extensions and features.

I presume that adding this new function (`are_extension_features_enabled`) also becomes easier with the addition of `enable_extension_features_if_present`.

**Comment by charles-lunarg** [comment]
Closed as the PR was merged
