### ISSUE TITLE
Incorrect warning setup for clang-cl

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#28]
The CMakeLists is incorrectly set up for clang-cl, because it is being detected as clang. This results in passing -Wall to clang-cl, which is translated into -Weverything, enabling a slew of C++98 warnings. Clang-cl should get the same flags as MSVC.

See https://github.com/KhronosGroup/SPIRV-Cross/pull/1316 and https://bugzilla.mozilla.org/show_bug.cgi?id=1476475 for more info and possible solution.

**Comment by charles-lunarg** [comment]
Fixed in the most recent commit.
