### ISSUE TITLE
[Fatal Error] [Segmentation Fault] in supports_features Function

### ISSUE THREAD

**Issue by imad23m** [charles-lunarg/vk-bootstrap#282]
Greetings.

I have been experiencing `Segmentation Fault` when starting my project, using GDB I got the following error:

`Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff722992736 in vkb::PhysicalDeviceSelector::is_device_suitable (this=0xb51c3fe5e0, pd=...) at ../dep/vk-bootstrap/src/VkBootstrap.cpp:1189
1189	    bool required_features_supported = detail::supports_features(`

The error happens only sometimes, not every instance, probably related to #91 

I couldn't manage to pin point where the issue in the function call itself happens, however changing all function arguments to pointers seem to have resolved the issue.

it seems sending complex objects in the function call results in some sort of memory issue, but not sure.

if any further information is needed, kindly let me know.

Thank You.

**Comment by charles-lunarg** [comment]
This is a failure that enabling address sanitizer would be the way to debug.

Can you share the code that is causing the error? (most usage of vk-bootstrap is localized to a single file so is easy to share). I'm hesitant to merge a fix for an undiagnosed crash.

**Comment by charles-lunarg** [comment]
Are you willing to try out a different branch of vk-bootstrap?
This uses references instead of passing by value. 
https://github.com/charles-lunarg/vk-bootstrap/tree/supports_features_use_references
