### ISSUE TITLE
`PhysicalDeviceSelector::select` crashes

### ISSUE THREAD

**Issue by n0F4x** [charles-lunarg/vk-bootstrap#289]
I get a SIGTRAP [right here](https://github.com/charles-lunarg/vk-bootstrap/blob/64fa0ebf5629601a0af767e1e9f12d6534362ed2/src/VkBootstrap.cpp#L1299) in the second iteration (for the second device).
The SIGTRAP happens inside the vector's `push_back` when folding its call stack.
But I'd guess the error is rather with the PhysicalDevice's (move/copy) constructor.

Environment: Clang (LLVM) 17.0.6

I couldn't test my project with other compilers as they all have some missing features.
The first commit that doesn't work is [here](https://github.com/charles-lunarg/vk-bootstrap/commit/c9d94287a5841cebddbc4d38195bd421dd2cd689).

**Comment by charles-lunarg** [comment]
Can you post your code? Hard to know what’s wrong without seeing how your code works.

**Comment by n0F4x** [comment]
[This](https://github.com/n0F4x/data-driven-game-engine/blob/105eb6999f99ae0ae853b08501527113ced8a30e/src/plugins/Renderer.cpp#L162) is where I call `PhysicalDevice::select` in my code

**Comment by n0F4x** [comment]
I am also suspicious of `PhysicalDevice::extended_features_chain` when it gets moved/copied. The pointers should still point to the right next feature.

**Comment by n0F4x** [comment]
I had a very weird setup where I was using an outdated VkBootstrap header.
Dropping that header and only using the new one runs fine.

So the problem was on my end.
