### ISSUE TITLE
`use_default_format_selection()` of the Swapchain builder result in a linear color space

### ISSUE THREAD

**Issue by LesleyLai** [charles-lunarg/vk-bootstrap#29]
```cpp
swapchain_builder
  .use_default_format_selection()
  .use_default_present_mode_selection()
  .build();
```
seems to resulting in a liner color space which is weird since the source code seems to want to use `VK_COLOR_SPACE_SRGB_NONLINEAR_KHR`.

Using
```cpp
.set_desired_format(VkSurfaceFormatKHR{
  .format = VK_FORMAT_B8G8R8A8_SRGB,
  .colorSpace = VK_COLOR_SPACE_SRGB_NONLINEAR_KHR,
})
```
manually can avoid this problem.

I need more investigation to see what is wrong.

**Comment by charles-lunarg** [comment]
Ah, I probably should be using `VK_FORMAT_B8G8R8A8_SRGB` instead of `VK_FORMAT_R8G8B8A8_UNORM` for the format.

I don't think there is any issue with the colorSpace however.

**Comment by LesleyLai** [comment]
I see.

**Comment by charles-lunarg** [comment]
Have fixed the format issue in the latest commit.
