### ISSUE TITLE
Make `GenericFeatureChain::add` compatible with Vulkan-Hpp

### ISSUE THREAD

**Issue by n0F4x** [charles-lunarg/vk-bootstrap#290]
```
error: invalid operands to binary expression ('const vk::StructureType' and 'VkStructureType')
  188 |             if (features.sType == node.sType) {
```

Using the library with the Vulkan C++ binding worked fine for me until [this commit](https://github.com/charles-lunarg/vk-bootstrap/commit/c9d94287a5841cebddbc4d38195bd421dd2cd689).

A quick fix is to insert a static_cast like so:

```
if (static_cast<VkStructureType>(features.sType) == node.sType) {
```

I don't know what the proper solution should be.

**Comment by charles-lunarg** [comment]
That is a fine solution as far as I'm concerned. The code is templated so it is good for it to accept either vulkan.h or vulkan-hpp types (especially considering they are binary compatible). Happy to accept this as a PR.
