### ISSUE TITLE
Small mistake in getting_started.md

### ISSUE THREAD

**Issue by Klark007** [charles-lunarg/vk-bootstrap#307]
Under the Swapchain header the code states

```cpp
[...]
vkb::swapchain swapchain = swap_ret.value();
```

but should be

```cpp
[...]
vkb::Swapchain swapchain = swap_ret.value();
```

**Comment by charles-lunarg** [comment]
Thanks! Documentation issues like that are easy to slip by but are very confusing for newcomers, so fixes are appreciated.
