### ISSUE TITLE
Add newer present modes

### ISSUE THREAD

**Issue by charles-lunarg** [charles-lunarg/vk-bootstrap#34]
VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR and VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR are supposedly how you can enable variable refresh rate presentation. It would be a nice to have. Will likely need to do feature checking first.

Documentation:
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPresentModeKHR.html

**Comment by martty** [comment]
AFAIK the SHARED_* WSI things are Android only.

**Comment by charles-lunarg** [comment]
Ack, I see. I'll close the issue as android isn't something I'm explicitly targeting. 
That isn't to say this wouldn't be useful if/when android support happens.
