### ISSUE TITLE
Static init order problem

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#35]
The new dynamic loading uses a variable of static storage duration (https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp#L197).

If a person (not named here) would use vk-bootstrap in static init code, this variable may not be initialized in time.
A solution would be to wrap the variable to ensure it is constructed:

```cpp
VulkanFunctions& vulkan_functions(){
  static VulkanFunctions v;
  return v;
}
```

**Comment by charles-lunarg** [comment]
Fixed in latest commit.
Thanks for pointing this out!
