### ISSUE TITLE
Loading incorrect extension on macOS

### ISSUE THREAD

**Issue by EthanMalin** [charles-lunarg/vk-bootstrap#37]
The extension loaded if __APPLE__ is defined during instance creation is incorrect. It is written as "VK_KHR_metal_surface" when it should be "VK_EXT_metal_surface". This causes instance creation to fail when using the library on mac with glfw.

**Comment by charles-lunarg** [comment]
Thank you for pointing this out!
Fixed in the most recent commit.
(You can blame the fact that all the other surface extensions are KHR, and I forgot to never assume.)
