### ISSUE TITLE
Add support for KHR raytracing extensions

### ISSUE THREAD

**Issue by charles-lunarg** [charles-lunarg/vk-bootstrap#38]
There are several function pointers which were added, and to support KHR raytracing need to be handled properly.

**Comment by vibi-manx** [comment]
What exactly needs to be handled here that is different from other extensions as far as enabling is concerned?

**Comment by charles-lunarg** [comment]
The requirements for the various extensions are listed here. 
https://www.khronos.org/blog/vulkan-ray-tracing-final-specification-release
But to copy/paste
```
VK_KHR_acceleration_structure requires:

* VK_KHR_deferred_host_operations
* accelerationStructure,
* descriptorBindingAccelerationStructureUpdateAfterBind,
* all the features required by the descriptorIndexing feature (if Vulkan 1.2 is supported) or the VK_EXT_descriptor_indexing extension, and
* bufferDeviceAddress from Vulkan 1.2 or the VK_KHR_buffer_device_address

Implementations that support VK_KHR_ray_tracing_pipeline require:

* VK_KHR_acceleration_structure,
* rayTracingPipeline,
* rayTracingPipelineTraceRaysIndirect,
* rayTraversalPrimitiveCulling, if VK_KHR_ray_query is also supported, and
* VK_KHR_pipeline_library.

Implementations that support VK_KHR_ray_query require:
* VK_KHR_acceleration_structure, and
* rayQuery.

Additionally there are a number of optional capabilities defined with the extensions.

For VK_KHR_acceleration_structure these are:

* accelerationStructureCaptureReplay,
* accelerationStructureIndirectBuild, and
* accelerationStructureHostCommands.

For VK_KHR_ray_tracing_pipeline these are:

* rayTracingPipelineShaderGroupHandleCaptureReplay,
* rayTracingPipelineShaderGroupHandleCaptureReplayMixed, and
* rayTraversalPrimitiveCulling, if VK_KHR_ray_query is not supported.

**Comment by charles-lunarg** [comment]
Additionally, the rational for function pointer loading is that to use raytracing KHR, it requires loading the function pointers directly. (just like debug utils)
Because KHR is a 'hot' extension, this is why it'd be something to do manually rather than add automatic function pointer getting. 
However, it is conceivable that function pointer loading is useful enough to warrant added auto-gen to create the dispatch tables.

**Comment by thargy** [comment]
Sorry for the n00b question, but does this mean that if I plan on using `KHR_ray-tracing` extensions I can't use `vk_bootstrap` or is it just that it "won't help"?

**Comment by charles-lunarg** [comment]
There is no issue using vk-bootstrap with KHR extensions. Its a bit more manual since you need to select the extensions directly, but there isn't any incompatibility between regular and raytracing stuff (as far as vk-bootstrap goes).

And because vk-bootstrap focuses on setting up instance/physical device/device/swapchain, it doesn't have any code path specific to raytracing (or rasterization) for that matter.

**Comment by charles-lunarg** [comment]
I'm going to close this issue since I didn't implement it, since the required extensions are split up to allow people to choose what they want, and that makes it hard to add a single "enable raytracing".
Feel free to disagree and re-open the issue.
