### ISSUE TITLE
Error: requested_extensions_not_present

### ISSUE THREAD

**Issue by seanbaxter** [charles-lunarg/vk-bootstrap#39]
I just tried this on the instance builder:
   .enable_extension("VK_EXT_buffer_device_address")

Program fails... What do I do?

**Comment by charles-lunarg** [comment]
It's a device extension, move this to `PhysicalDeviceBuilder`'s `add_required_extension("VK_EXT_buffer_device_address")`.

**Comment by seanbaxter** [comment]
I'm new to this. Thx.
