### ISSUE TITLE
Confusion between require_dedicated_compute_queue and require_dedicated_transfer_queue/require_separate_compute_queue and require_separate_transfer_queue

### ISSUE THREAD

**Issue by ethindp** [charles-lunarg/vk-bootstrap#50]
The class header does not enumerate the difference between requiring a dedicated and separate queue and how that alters the creation process (e.g.: do I still get a graphics queue, or do I only get a compute/transfer queue?). The documentation also does not enumerate these differences.

**Comment by charles-lunarg** [comment]
The pattern I saw when I was designing the queue family selection logic was that on some hardware there were dedicated compute and/or transfer queues and on other hardware there was merely queues that had transfer + compute capabilities but not separate queue families for each.

The intent of 'dedicated' is compute or transfer and nothing else while separate is a queue that will do at least one of the two (compute and/or transfer). 

In retrospect, I think this doesn't make for a very obvious distinction but it is a result of the very diverse combinations of queue families that exist in the wild. Requiring any option indicates that the device must support what ever is being required, in addition to a graphics queue. There is certainly a place for a 'doesn't need to support graphics queue' hardware. 

Additionally, I am not 100% that the logic currently in place will do the right thing always. This is a place I need to add some unit tests for the various hardware configs to make sure the selection logic 'does the right thing' like find the best fit and not the first fit, which is the current logic.

**Comment by ethindp** [comment]
Okay, that makes sense. Thanks for that clarification!
