### ISSUE TITLE
Document which extensions are automatically enabled

### ISSUE THREAD

**Issue by DethRaid** [charles-lunarg/vk-bootstrap#6]
Please document which instance and device extensions are enabled in the comments for the instance and device builder. For instance, it seems like the swapchain and surface extensions are enabled by the builder itself? But I'm not sure

**Comment by charles-lunarg** [comment]
More thorough documentation is definitely needed. Its being held off until the meat and potatoes of the API is mostly stable. Leaving it open as a reminder when that document gets written.

**Comment by charles-lunarg** [comment]
Since there is now a mention that the extensions are passed on and that there is a dedicated extension issue, I will close this issue. No sense having two issues which refer to the same problem
