### ISSUE TITLE
Remove `InstanceBuilder::check_and_add_layer`, `InstanceBuilder::check_and_add_extension`, and `InstanceBuilder::check_and_setup_validation_layers`

### ISSUE THREAD

**Issue by DethRaid** [charles-lunarg/vk-bootstrap#7]
These methods check if various extensions and layers are available, and enables them if they are. I have two main problems with these methods:

* No good way to report failure without breaking the builder interface. They might be better as free functions
* You can check which extensions and layers are available in `InstanceBuilder::build`. This makes more sense to me. I just have a gut feeling that a builder shouldn't perform any validation until I request building

**Comment by charles-lunarg** [comment]
I have introduced a `SystemInfo` struct that the user can request from the InstanceBuilder. This has member functions `is_layer_available` and `is_extension_available`. It also has public booleans for `validation_layers_available` and `debug_messenger_available`.

**Comment by charles-lunarg** [comment]
There is now only one way to add a layer/extension to InstanceBuilder, and if any layers/extensions in the list aren't supported the instance builder will fail. 
Generally, if you are adding extensions or layers, you need them to work. If you don't, you will need to check if they are available first, which is accomplished through the SystemInfo struct.
