### ISSUE TITLE
vkDestroySurfaceKHR address must be retrieved with vkGetInstanceProcAddr()

### ISSUE THREAD

**Issue by YvesBoyadjian** [charles-lunarg/vk-bootstrap#71]
With an AMD driver, vkDestroySurfaceKHR is null, leading to a crash when exiting triangle demo:

[https://forums.developer.nvidia.com/t/vkgetdeviceprocaddr-and-vkdestroysurfacekhr/43383](url)

So the right code in "common.h" is: 

	void init(VkInstance instance) {
		vkGetDeviceProcAddr = (PFN_vkGetDeviceProcAddr)vkGetInstanceProcAddr(instance, "vkGetDeviceProcAddr");
		vkDestroySurfaceKHR = (PFN_vkDestroySurfaceKHR)vkGetInstanceProcAddr(instance, "vkDestroySurfaceKHR");
	}

**Comment by charles-lunarg** [comment]
I actually discovered this issue on my own the other night, but thank you for reporting it.
I'll make a change shortly, since it is a very annoying bug to have in the example.

**Comment by charles-lunarg** [comment]
Fixed now, pull master and it should not crash anymore.
(The commit was in a different PR that I had forgotten to merge)
