### ISSUE TITLE
Inverted test in SystemInfo constructor

### ISSUE THREAD

**Issue by YvesBoyadjian** [charles-lunarg/vk-bootstrap#73]
In line 544 of VkBootstrap.cpp, there is the code:

`		if (layer_extensions_ret != VK_SUCCESS) {`

it should be:
`		if (layer_extensions_ret == VK_SUCCESS) {`

**Comment by charles-lunarg** [comment]
Right you are! It would be a really easy thing for me to fix, but I'm open to accepting a PR instead of making a fix for it myself.

**Comment by YvesBoyadjian** [comment]
Did a PR:
[https://github.com/charles-lunarg/vk-bootstrap/pull/74](url)

**Comment by charles-lunarg** [comment]
Thanks!
