### ISSUE TITLE
Hangs on InstanceBuilder.build()...but only sometimes??

### ISSUE THREAD

**Issue by kaifastromai** [charles-lunarg/vk-bootstrap#91]
Very new to Vulkan, so forgive me for any misconceptions I might have. 
I am running on the latest version of windows Windows 10 with a Titan X GPU and Xeon CPU
 I am creating a new instance like so: 

```c++
 vkb::InstanceBuilder builder;
	auto inst_ret =builder.set_app_name("Skie")
	.require_api_version(1, 1, 2).
	enable_validation_layers(false).build();
```

I've isolated it such that this is more or less the only thing the application is doing. Sometimes this works perfectly, however periodically, it will hang indefinitely. I've traced the point to line 711 (ish) in the main .cpp file, which looks like
```c++
VkResult res = detail::vulkan_functions().fp_vkCreateInstance(
	    &instance_create_info, info.allocation_callbacks, &instance.instance)
```
It seems that the call to vkCreateInstance never returns the flow of control (so I can't even inspect any return values). The validation layers aren't of any help either. Debugging in MSVC, the moment this line is reached, the debugger just hangs. The part that really perplexes me is why it only happens sometimes. If you have any insights, they would be most appreciated!

**Comment by kaifastromai** [comment]
The only part that matters is the call to init_vulkan.

**Comment by charles-lunarg** [comment]
Apologies for not getting back sooner.
Is this still an issue? Trying to gauge if I should try to build the repo and debug it.

**Comment by charles-lunarg** [comment]
Cleaning up old issues - I have a feeling this is due to a specific combination of driver, implicit layers, and the phase of the moon. Could be a bug in vk-bootstrap for sure, and could be a bug with a weird interaction between vk-bootstrap and the way the project is setup. I'm going to close this issue but feel free to reopen if you are still having this issue.
