### ISSUE TITLE
Trying to create two Instances results in a Crash

### ISSUE THREAD

**Issue by Ipotrick** [charles-lunarg/vk-bootstrap#98]
I can not create two Vulkan instances with the vkb::InstaneBuilder. A minimal reproducable example:
```
#include "VkBootstrap.h"

int main()
{
	vkb::InstanceBuilder instanceBuilder;
	auto instanceBuildReturn = instanceBuilder.build();
	vkb::InstanceBuilder instanceBuilder2;
	auto instanceBuildReturn2 = instanceBuilder2.build(); //<= crash here
}
```

The Program crashes when it tries to dereference detail::vulkan_functions().fp_vkEnumerateInstanceLayerProperties) inside the function SystemInfo::SystemInfo(), but the pointer fp_vkEnumerateInstanceLayerProperties is a nullptr in the second build invocation!
It seems to me that some of the loaded function pointers inside the info struct get lost somehow.

I am building this with the latest Vulkan sdk Version: 1.2.198.
Notable is that i use the Nvidia Beta Drivers (Version 472.77 on a GTX 1080ti), so this could be a bug in the beta drivers!
EDIT: I now also tried the latest stable drivers adn the problem still persists.
Windows Version: Windows 10 Pro 19042.1348.

**Comment by Ipotrick** [comment]
I have tested this with two other PC's and it only crashes on my main one. I dont have any other problems compiling/running code on that machiene tho. 
I also think that this only started to happen after a windows update, so it might be a weird bug thats dependant on windows.

**Comment by Ipotrick** [comment]
This error seems to be a problem with my system, not the library. After reinstalling msvc the error went away.

**Comment by Ipotrick** [comment]
After getting to know that other people can reproduce the crash, i think its actually a bug in vkboostrap and not a weird setup problem on my pc.

**Comment by charles-lunarg** [comment]
This has now been fixed in master.
Thanks for reporting it!
It indeed is *super* weird behavior. And I apologize for causing such headaches.
