### ISSUE TITLE
[Linux] segfault on vkGetPhysicalDeviceFeatures2KHR

### ISSUE THREAD

**Issue by spnda** [charles-lunarg/vk-bootstrap#99]
As seen in the below snippet, vk-bootstrap checks if the Vulkan API version is newer than 1.1 and if so, uses the core version of `vkGetPhysicalDeviceFeatures2` so it doesn't have to enable the extension. However, on my Linux machine, it somehow doesn't go that route and and tries calling `vkGetPhysicalDeviceFeatures2KHR`, which is `nullptr` and therefore causes a segfault. Commenting out that line and the application runs fine. My instance info API version is `1.2.0` and my device reports as `1.2.186`. This doesn't happen on my Windows machine, which leads me to believe it's some Linux driver specific issue possibly?

https://github.com/charles-lunarg/vk-bootstrap/blob/142986cdb767037118b687387b097ff6b3e7fe7d/src/VkBootstrap.cpp#L1047-L1051

**Comment by charles-lunarg** [comment]
So you are setting the instance version to 1.1+ and the device is 1.2.186...

Is there any physical devices on the system that are 1.0?

**Comment by spnda** [comment]
> Is there any physical devices on the system that are 1.0?

Yes, there's a llvmpipe available which is at Vulkan 1.0.2, however my application itself reports the VkDevice is my RTX 2080, which is at 1.2.186.

**Comment by charles-lunarg** [comment]
I *think* its related to this issue: https://github.com/KhronosGroup/Vulkan-Loader/pull/779

It'd be really awesome if you could build the loader with that PR and run with that build. vk-bootstrap likely has a bug here too but the loader isn't helping.

**Comment by spnda** [comment]
> It'd be really awesome if you could build the loader with that PR and run with that build. 

I don't have much time currently but I'll try when my holidays start on Wednesday. Thanks for the tip 👍🏻

**Comment by charles-lunarg** [comment]
The vk-bootstrap code probably doesn't enable the extension when it should and thinks the extension is enabled in the code bit you provide.

**Comment by spnda** [comment]
I think it's correct it doesn't enable the extension as the VkPhysicalDevice is in fact my 2080 which is Vulkan 1.2. But in that snippet it thinks it needs the extension and thinks its activated even though it isn't and therefore segfaults on that function pointer being null.
